- name: bug
  color: d73a4a
  description: Something isn't working

- name: chore
  color: ffffff
  description: Build process or auxiliary tool changes

- name: feature request
  color: 0075ca
  description: New feature or request

- name: duplicate
  color: cfd3d7
  description: This issue or pull request already exists

- name: blocked
  color: d73a4a
  description: Action required to proceed

- name: dependencies
  color: d93f0b
  description: Dependency updates!!
