"dependencies":
  - changed-files:
      - any-glob-to-any-file:
          - "pnpm-lock.yaml"
          - "package.json"
          - "packages/*/package.json"

"e:simple-chat-app":
  - changed-files:
      - any-glob-to-any-file: ["examples/simple-chat-app/**"]

"e:with-custom-server":
  - changed-files:
      - any-glob-to-any-file: ["examples/with-custom-server/**"]

"p:cli":
  - changed-files:
      - any-glob-to-any-file: ["packages/cli/**"]

"p:core":
  - changed-files:
      - any-glob-to-any-file: ["packages/core/**"]
