"dependencies":
  - changed-files:
      - any-glob-to-any-file: ["pnpm-lock.yaml"]

"client":
  - changed-files:
      - any-glob-to-any-file: ["src/client/**"]

"server":
  - changed-files:
      - any-glob-to-any-file: ["src/server/**"]

"patches":
  - changed-files:
      - any-glob-to-any-file: ["src/patches/**"]

"cli":
  - changed-files:
      - any-glob-to-any-file: ["src/cli.ts", "src/commands/**"]

"examples":
  - changed-files:
      - any-glob-to-any-file: ["examples/**"]

"tests":
  - changed-files:
      - any-glob-to-any-file: ["tests/**"]
