name: Setup Node.js
description: Setup Node.js, PNPM, and install dependencies

runs:
  using: "composite"
  steps:
    - uses: pnpm/action-setup@v4

    - name: Setup Node.js environment
      uses: actions/setup-node@v3
      with:
        node-version: 20
        registry-url: "https://registry.npmjs.org"
        cache: pnpm

    - name: Install dependencies
      run: pnpm install
      shell: bash
