name: Bump Next.js Version

on:
  # TODO: Test this when the next version of Next.js is released
  # schedule:
  #   - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  check-next-version:
    name: Check for New Next.js Version
    runs-on: ubuntu-latest
    outputs:
      current_version: ${{ steps.get-current-version.outputs.current_version }}
      latest_version: ${{ steps.get-latest-version.outputs.latest_version }}
      bump_needed: ${{ steps.compare-versions.outputs.bump_needed }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: ./.github/actions/node

      - name: Get Current Next.js Version
        id: get-current-version
        run: |
          current_version=$(pnpm list next | grep -o 'next [0-9].*' | cut -d ' ' -f 2)
          echo "current_version=$current_version" >> $GITHUB_OUTPUT

      - name: Get Latest Next.js Version
        id: get-latest-version
        run: |
          latest_version=$(npm show next version)
          echo "latest_version=$latest_version" >> $GITHUB_OUTPUT

      - name: Compare Versions
        id: compare-versions
        run: |
          if [ "$latest_version" != "$current_version" ]; then
            echo "bump_needed=true" >> $GITHUB_OUTPUT
          else
            echo "bump_needed=false" >> $GITHUB_OUTPUT

  update-next-version:
    name: Bump Next.js Version
    runs-on: ubuntu-latest
    if: ${{ needs.check-next-version.outputs.bump_needed == 'true' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: ./.github/actions/node

      - name: Update Next.js Version
        run: pnpm update next@latest -r

      - name: Bump Supported Range
        run: |
          new_version="${{ needs.check-next-version.outputs.latest_version }}"
          patch_file=$(ls src/patches/patch-*.ts | sort -V | tail -n 1)
          sed -i "s/\(versions: .*\) <=[0-9\.]\+/\1 <=$new_version/" "$patch_file"

      - name: Make Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Bump patch supported range to ${{ needs.check-next-version.outputs.latest_version }}"
          branch: "bump-next-version"
          title: "Bump patch supported range to ${{ needs.check-next-version.outputs.latest_version }}"
          body: "Bump patch supported range to ${{ needs.check-next-version.outputs.latest_version }}"
          delete-branch: true
