name: Continuous Integration

on:
  push:
  pull_request:
  workflow_dispatch:
  workflow_call:

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Workflow
        uses: ./.github/actions/setup

      - name: Run Linter
        run: pnpm lint

  build:
    name: Building
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Workflow
        uses: ./.github/actions/setup

      - name: Build project
        run: pnpm build
