name: Continuous Integration

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]
  workflow_dispatch:
  workflow_call:

jobs:
  check:
    name: Type Checking
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Workflow
        uses: ./.github/actions/setup

      - name: Run Type Checker
        run: pnpm check

  quality:
    name: Quality Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Workflow
        uses: ./.github/actions/setup

      - name: Run Quality Checks
        run: pnpm quality

  build:
    name: Building
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Workflow
        uses: ./.github/actions/setup

      - name: Build project
        run: pnpm build

  test:
    name: Testing
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Workflow
        uses: ./.github/actions/setup

      - name: Install browsers
        run: pnpm playwright install --with-deps

      - name: Run tests
        run: pnpm test

      - name: Upload test report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: tests/.report/
          include-hidden-files: true
          retention-days: 7

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: test-results
          path: tests/.results/
          include-hidden-files: true
          retention-days: 7
