name: PR Triage

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  label:
    name: Label Pull Request
    if: github.event.action != 'edited'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Label pull request
        uses: actions/labeler@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/pr-labels.yml
          sync-labels: true
