name: Publish Snapshots

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "packages/**"
      - "package.json"

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Workflow
        uses: ./.github/actions/setup

      - name: Publish Snapshots
        run: pnpm run publish:snapshot
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
