name: Pull Request Triage

on:
  - pull_request_target

jobs:
  label:
    name: Label Pull Request
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Apply pull request labels
        uses: actions/labeler@v5
        with:
          configuration-path: .github/pr-labels.yml
